
name: Lint Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      id: cp311
      with:
        python-version: 3.11

    - name: Cache Dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

    - name: Install pip Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install .[dev]

    - uses: chartboost/ruff-action@v1

    - uses: chartboost/ruff-action@v1
      with:
        args: 'format --check'
    
    - name: Run mypy
      run: mypy src/SideBot
